spring:
  application:
    name: ondosee
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

vworld:
  key: ${VWORLD_KEY}

dataporter:
  key: ${DATAPORTER_KEY}

openweather:
  key: ${OPENWATER_KEY}