spring:
  application:
    name: ondosee
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}


  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

vworld:
  key: ${VWORLD_KEY}

dataporter:
  key: ${DATAPORTER_KEY}

openweather:
  key: ${OPENWATER_KEY}

fcm:
  url: ${FCM_URL}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      url: ${AWS_URL}
    stack:
      auto: false